[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  bblanchon/ArduinoJson
  marcoschwartz/LiquidCrystal_I2C
  smarmengol/Modbus-Master-Slave-for-Arduino
  h2zero/NimBLE-Arduino
  links2004/WebSockets
  adafruit/MAX6675 library
