[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  https://github.com/bblanchon/ArduinoJson.git
  https://github.com/marcoschwartz/LiquidCrystal_I2C.git
  https://github.com/smarmengol/Modbus-Master-Slave-for-Arduino.git
  https://github.com/h2zero/NimBLE-Arduino.git
  https://github.com/Links2004/arduinoWebSockets.git
  https://github.com/adafruit/MAX6675-library.git
